name: CI

on:
  push:
    branches:
      - main
      - 'dependabot/**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies && npm --version
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    name: Test on Node.js ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      # HACK: See https://github.com/npm/cli/issues/4341
      - name: Workaround for npm installation failure on Node.js 14 and Windows
        if: ${{ startsWith(matrix.node, '14') && startsWith(matrix.os, 'windows') }}
        run: npm install --global npm@8.3

      - name: Install latest npm
        run: npm install --global npm@latest && npm --version

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test
